### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by taylorreiter** [fteufel/DeepPeptide#4]
I recently switched to running DeepPeptide on a GPU, and encountered the following errors using the `predict.py` script.

```
Traceback (most recent call last):
  File "/home/ubuntu/peptigate/cloned_repositories/DeepPeptide/predictor/predict.py", line 204, in <module>
    main()
  File "/home/ubuntu/peptigate/cloned_repositories/DeepPeptide/predictor/predict.py", line 118, in main
    features = model.feature_extractor(embeddings.permute(0,2,1), mask)
  File "/home/ubuntu/peptigate/.snakemake/conda/7e9a67fd8826e890b8d81e2579c44625_/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/peptigate/cloned_repositories/DeepPeptide/predictor/model.py", line 57, in forward
    out = self.ReLU(self.conv1(out))  # [batch_size,embeddings_dim,sequence_length] -> [batch_size,32,sequence_length]
  File "/home/ubuntu/peptigate/.snakemake/conda/7e9a67fd8826e890b8d81e2579c44625_/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/peptigate/.snakemake/conda/7e9a67fd8826e890b8d81e2579c44625_/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 302, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ubuntu/peptigate/.snakemake/conda/7e9a67fd8826e890b8d81e2579c44625_/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 298, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
```

I fixed this error with:
```
109             embeddings = embeddings.to(device)
110             mask = mask.to(device)
111
112             batch_emissions = []
113             batch_marginals = []
114             for model in models:
115                 model = model.to(device)
116                 model.eval()
```

but then got the error:
```
Traceback (most recent call last):
  File "/home/ubuntu/peptigate/cloned_repositories/DeepPeptide/predictor/predict.py", line 204, in <module>
    main()
  File "/home/ubuntu/peptigate/cloned_repositories/DeepPeptide/predictor/predict.py", line 129, in main
    ensemble_paths, ensemble_path_llhs = crf.decode(batch_emissions.to(device), mask.byte(), top_k=1)
  File "/home/ubuntu/peptigate/cloned_repositories/DeepPeptide/predictor/crf.py", line 226, in decode
    paths, likelihoods = self._viterbi_decode(emissions, mask)
  File "/home/ubuntu/peptigate/cloned_repositories/DeepPeptide/predictor/crf.py", line 411, in _viterbi_decode
    score = self.start_transitions + emissions[0]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

which I wasn't sure how to fix

**Comment by fteufel** [comment]
Thanks for reporting all these issues! I've added the missing device casts.
